import type { ProjectProfile } from "../core/types.js";
import { json } from "../utils/fs.js";
import type { TemplateFile } from "./template-types.js";

export function chromeExtensionFiles(profile: ProjectProfile): TemplateFile[] {
  return [
    {
      path: "package.json",
      content: json({
        name: profile.name,
        version: "0.1.0",
        type: "module",
        scripts: {
          check:
            "node --check src/background/index.js && node --check src/content/index.js && node --check src/popup/index.js && node --check src/shared/messages.js",
          package: "node scripts/package-extension.js",
          test: "npm run check",
          build: "npm run package"
        },
        devDependencies: {}
      })
    },
    {
      path: "manifest.json",
      content: json({
        manifest_version: 3,
        name: "{{projectTitle}}",
        version: "0.1.0",
        description: "AI-native Chrome extension generated by AgentKick.",
        action: { default_popup: "src/popup/index.html" },
        background: { service_worker: "src/background/index.js", type: "module" },
        content_scripts: [{ matches: ["<all_urls>"], js: ["src/content/index.js"], run_at: "document_idle" }],
        permissions: ["storage"]
      })
    },
    {
      path: "src/background/index.js",
      content: `import { MESSAGE_TYPES } from "../shared/messages.js";

chrome.runtime.onInstalled.addListener(() => {
  chrome.storage.local.set({ installedAt: Date.now() });
});

chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
  if (message?.type !== MESSAGE_TYPES.PING) return false;
  sendResponse({ ok: true, scope: "background" });
  return true;
});
`
    },
    {
      path: "src/content/index.js",
      content: `const MESSAGE_TYPE = "agentkick:ping";

chrome.runtime.sendMessage({ type: MESSAGE_TYPE, source: "content" }).catch(() => {
  // The background worker may be unavailable on restricted pages.
});
`
    },
    {
      path: "src/shared/messages.js",
      content: `export const MESSAGE_TYPES = Object.freeze({
  PING: "agentkick:ping"
});
`
    },
    {
      path: "src/popup/index.html",
      content: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="./styles.css">
    <title>{{projectTitle}}</title>
  </head>
  <body>
    <main>
      <section class="panel">
        <p class="eyebrow">Extension</p>
        <h1>{{projectTitle}}</h1>
        <p id="status">Ready</p>
        <button id="check" type="button">Check worker</button>
      </section>
    </main>
    <script type="module" src="./index.js"></script>
  </body>
</html>
`
    },
    {
      path: "src/popup/index.js",
      content: `import { MESSAGE_TYPES } from "../shared/messages.js";

const button = document.querySelector("#check");
const status = document.querySelector("#status");

button?.addEventListener("click", async () => {
  status.textContent = "Checking...";
  try {
    const response = await chrome.runtime.sendMessage({ type: MESSAGE_TYPES.PING, source: "popup" });
    status.textContent = response?.ok ? "Background worker ready." : "No response.";
  } catch (error) {
    status.textContent = error instanceof Error ? error.message : "Unable to reach background worker.";
  }
});
`
    },
    {
      path: "src/popup/styles.css",
      content: `:root {
  color-scheme: light;
  --bg: #f7f8fb;
  --ink: #101827;
  --muted: #5d6678;
  --line: #d6deea;
  --accent: #1f5eff;
}

body {
  margin: 0;
  width: 360px;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  background: var(--bg);
  color: var(--ink);
}

main {
  padding: 16px;
}

.panel {
  border: 1px solid var(--line);
  border-radius: 8px;
  background: white;
  padding: 16px;
}

.eyebrow {
  margin: 0 0 8px;
  color: var(--muted);
  font-size: 12px;
  text-transform: uppercase;
}

h1 {
  margin: 0 0 12px;
  font-size: 20px;
}

button {
  width: 100%;
  border: 0;
  border-radius: 6px;
  padding: 10px 12px;
  background: var(--accent);
  color: white;
  font-weight: 700;
  cursor: pointer;
}
`
    },
    {
      path: "scripts/package-extension.js",
      content: `import fs from "node:fs";
import path from "node:path";

const dist = path.resolve("dist");
fs.rmSync(dist, { recursive: true, force: true });
fs.mkdirSync(dist, { recursive: true });
fs.cpSync("manifest.json", path.join(dist, "manifest.json"));
fs.cpSync("src", path.join(dist, "src"), { recursive: true });
console.log("Extension package prepared in dist/");
`
    },
    {
      path: "src/features/README.md",
      content: `# Extension Features

Keep feature code grouped by browser surface:

- \`background\`: service worker and durable browser events
- \`content\`: page interaction layer
- \`popup\`: user interface
- \`shared\`: message contracts and stable utilities
`
    }
  ];
}
