import type { ProjectProfile } from "../core/types.js";
import { json } from "../utils/fs.js";
import type { TemplateFile } from "./template-types.js";

export function aiSaasFiles(profile: ProjectProfile): TemplateFile[] {
  return [
    ...nextPackageFiles(profile, "AI SaaS application generated by AgentKick."),
    ...nextBaseFiles(
      "Build the AI workflow layer first.",
      "Design workflows that agents can understand and users can trust."
    ),
    {
      path: "app/api/workflows/route.ts",
      content: `import { NextResponse } from "next/server";
import { listWorkflowRuns } from "@/src/features/workflows/server/workflow-service";

export async function GET() {
  return NextResponse.json({ workflows: listWorkflowRuns() });
}
`
    },
    {
      path: "src/features/workflows/server/workflow-service.ts",
      content: `export type WorkflowRun = {
  id: string;
  name: string;
  status: "queued" | "running" | "complete";
};

const runs: WorkflowRun[] = [
  { id: "demo-onboarding", name: "Onboarding analysis", status: "queued" }
];

export function listWorkflowRuns() {
  return runs;
}
`
    },
    {
      path: "src/features/workflows/README.md",
      content: `# Workflows

Owns AI workflow runs, execution state, and task handoff boundaries.

Agents should keep prompt, execution, and result handling separate in this feature.
`
    },
    {
      path: "src/features/memory/README.md",
      content: `# Memory

Owns durable project and customer-facing memory. Do not store secrets here.

Use small typed records and summarize long-running state before it enters prompts.
`
    },
    {
      path: "src/core/env.ts",
      content: `export function requiredEnv(name: string) {
  const value = process.env[name];
  if (!value) throw new Error(\`Missing required environment variable: \${name}\`);
  return value;
}
`
    }
  ];
}

export function saasFiles(profile: ProjectProfile): TemplateFile[] {
  return [
    ...nextPackageFiles(profile, "SaaS application generated by AgentKick."),
    ...nextBaseFiles(
      "Build the smallest useful customer workspace.",
      "Keep account, billing, and workspace boundaries explicit."
    ),
    {
      path: "src/features/accounts/README.md",
      content: `# Accounts

Owns user, organization, and membership behavior.

Do not mix billing or product workflow behavior into this module.
`
    },
    {
      path: "src/features/billing/README.md",
      content: `# Billing

Owns plans, subscriptions, invoices, and payment-provider boundaries.

Agents must call out migration impact before changing billing contracts.
`
    },
    {
      path: "src/features/workspaces/README.md",
      content: `# Workspaces

Owns the customer workspace shell and scoped project data.
`
    },
    {
      path: "app/api/health/route.ts",
      content: `import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({ ok: true, service: "{{projectName}}" });
}
`
    }
  ];
}

export function marketplaceFiles(profile: ProjectProfile): TemplateFile[] {
  return [
    ...nextPackageFiles(profile, "Marketplace application generated by AgentKick."),
    ...nextBaseFiles(
      "Build the marketplace trust loop first.",
      "Keep vendor, listing, order, and admin modules isolated."
    ),
    {
      path: "src/features/vendors/README.md",
      content: `# Vendors

Owns seller onboarding, profiles, approval state, and vendor operations.
`
    },
    {
      path: "src/features/listings/README.md",
      content: `# Listings

Owns catalog items, availability, pricing display, and listing quality checks.
`
    },
    {
      path: "src/features/orders/README.md",
      content: `# Orders

Owns checkout handoff, order lifecycle, fulfillment state, and customer updates.
`
    },
    {
      path: "src/features/admin/README.md",
      content: `# Admin

Owns marketplace moderation, trust operations, and support workflows.
`
    },
    {
      path: "app/api/marketplace/route.ts",
      content: `import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({
    vendors: [],
    listings: [],
    orders: []
  });
}
`
    }
  ];
}

function nextPackageFiles(profile: ProjectProfile, description: string): TemplateFile[] {
  return [
    {
      path: "package.json",
      content: json({
        name: profile.name,
        version: "0.1.0",
        private: true,
        description,
        scripts: { dev: "next dev", build: "next build", start: "next start", test: "npm run build" },
        dependencies: { next: "latest", react: "latest", "react-dom": "latest" },
        devDependencies: {
          typescript: "latest",
          "@types/node": "latest",
          "@types/react": "latest",
          "@types/react-dom": "latest"
        }
      })
    },
    {
      path: "tsconfig.json",
      content: json({
        compilerOptions: {
          target: "ES2017",
          lib: ["dom", "dom.iterable", "esnext"],
          allowJs: false,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: "esnext",
          moduleResolution: "bundler",
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: "preserve",
          incremental: true,
          paths: { "@/*": ["./*"] }
        },
        include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
        exclude: ["node_modules"]
      })
    },
    { path: "next.config.mjs", content: "const nextConfig = {};\nexport default nextConfig;\n" }
  ];
}

function nextBaseFiles(headline: string, subheadline: string): TemplateFile[] {
  return [
    {
      path: "app/layout.tsx",
      content: `import type { ReactNode } from "react";
import "./globals.css";

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`
    },
    {
      path: "app/page.tsx",
      content: `export default function Home() {
  return (
    <main className="shell">
      <section>
        <p className="eyebrow">AgentKick Project</p>
        <h1>${headline}</h1>
        <p>${subheadline}</p>
      </section>
    </main>
  );
}
`
    },
    {
      path: "app/globals.css",
      content: `:root {
  color-scheme: light;
  --bg: #f7f8fb;
  --ink: #111827;
  --muted: #5d6678;
  --accent: #1f5eff;
}

body {
  margin: 0;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  background: var(--bg);
  color: var(--ink);
}

.shell {
  min-height: 100vh;
  width: min(960px, calc(100% - 32px));
  margin: 0 auto;
  display: grid;
  align-content: center;
}

.eyebrow {
  margin: 0 0 12px;
  color: var(--muted);
  font-size: 12px;
  text-transform: uppercase;
}

h1 {
  max-width: 760px;
  margin: 0 0 18px;
  font-size: clamp(40px, 8vw, 84px);
  line-height: 0.98;
}

p {
  max-width: 680px;
  font-size: 20px;
  line-height: 1.6;
}
`
    },
    {
      path: "src/core/README.md",
      content: `# Core

Shared framework-neutral code lives here. Keep this folder small and stable.
`
    },
    {
      path: "src/shared/README.md",
      content: `# Shared

Reusable utilities and presentational pieces that do not own product behavior.
`
    }
  ];
}
