import { json, writeFile } from "./fs-utils.js";
import { readmeFor } from "./agent-files.js";
import type { ProjectProfile } from "./types.js";

export function writeTemplateProject(projectDir: string, profile: ProjectProfile) {
  switch (profile.template) {
    case "chrome-extension":
      writeChromeExtension(projectDir, profile);
      break;
    case "nextjs":
      writeNextjs(projectDir, profile);
      break;
    case "landing-page":
      writeLandingPage(projectDir, profile);
      break;
    case "node-cli":
      writeNodeCli(projectDir, profile);
      break;
    case "fastapi":
      writeFastApi(projectDir, profile);
      break;
    case "flask":
      writeFlask(projectDir, profile);
      break;
    case "laravel":
      writeLaravel(projectDir, profile);
      break;
    case "go-cli":
      writeGoCli(projectDir, profile);
      break;
    case "rust-cli":
      writeRustCli(projectDir, profile);
      break;
    case "electron":
      writeElectron(projectDir, profile);
      break;
    default:
      throw new Error(`template writer missing for "${profile.template}"`);
  }

  writeFile(projectDir, "README.md", readmeFor(profile));
  writeFile(projectDir, ".gitignore", gitignoreFor(profile));
}

function writeChromeExtension(projectDir: string, profile: ProjectProfile) {
  writeFile(
    projectDir,
    "package.json",
    json({
      name: profile.name,
      version: "0.1.0",
      type: "module",
      scripts: {
        check: "node --check src/background.js && node --check src/popup.js",
        package: "node scripts/package-extension.js",
        test: "npm run check"
      },
      devDependencies: {}
    })
  );
  writeFile(
    projectDir,
    "manifest.json",
    json({
      manifest_version: 3,
      name: titleize(profile.name),
      version: "0.1.0",
      description: "Chrome extension scaffold generated by AgentKick.",
      action: { default_popup: "src/popup.html" },
      background: { service_worker: "src/background.js", type: "module" },
      permissions: ["storage"]
    })
  );
  writeFile(
    projectDir,
    "src/background.js",
    "chrome.runtime.onInstalled.addListener(() => {\n  console.log('Extension installed.');\n});\n"
  );
  writeFile(
    projectDir,
    "src/popup.html",
    htmlPage(
      "AgentKick Extension",
      '<button id="run">Run</button>\n      <p id="status">Ready</p>',
      '<script type="module" src="popup.js"></script>'
    )
  );
  writeFile(
    projectDir,
    "src/popup.css",
    "body { margin: 0; width: 360px; font-family: Georgia, serif; background: #f5efe2; color: #221b14; }\nmain { padding: 18px; }\nbutton { border: 0; border-radius: 999px; padding: 10px 14px; background: #1f5134; color: white; cursor: pointer; }\n"
  );
  writeFile(
    projectDir,
    "src/popup.js",
    "const button = document.querySelector('#run');\nconst status = document.querySelector('#status');\n\nbutton.addEventListener('click', () => {\n  status.textContent = 'Clicked.';\n});\n"
  );
  writeFile(
    projectDir,
    "scripts/package-extension.js",
    "import fs from 'node:fs';\nimport path from 'node:path';\n\nconst outDir = path.resolve('dist');\nfs.mkdirSync(outDir, { recursive: true });\nconsole.log('Package step placeholder. Add zip creation before publishing.');\n"
  );
}

function writeNextjs(projectDir: string, profile: ProjectProfile) {
  writeFile(
    projectDir,
    "package.json",
    json({
      name: profile.name,
      version: "0.1.0",
      private: true,
      scripts: { dev: "next dev", build: "next build", start: "next start", test: "npm run build" },
      dependencies: { next: "latest", react: "latest", "react-dom": "latest" },
      devDependencies: { typescript: "latest", "@types/node": "latest", "@types/react": "latest" }
    })
  );
  writeFile(
    projectDir,
    "app/page.tsx",
    "export default function Home() {\n  return (\n    <main>\n      <h1>AgentKick Next.js App</h1>\n      <p>Start building with agent-ready project instructions.</p>\n    </main>\n  );\n}\n"
  );
  writeFile(
    projectDir,
    "app/layout.tsx",
    "import type { ReactNode } from 'react';\nimport './globals.css';\n\nexport default function RootLayout({ children }: { children: ReactNode }) {\n  return (\n    <html lang=\"en\">\n      <body>{children}</body>\n    </html>\n  );\n}\n"
  );
  writeFile(
    projectDir,
    "app/globals.css",
    "body { margin: 0; font-family: Georgia, serif; background: #f6f0e6; color: #1f1b16; }\nmain { min-height: 100vh; display: grid; place-content: center; padding: 32px; }\n"
  );
  writeFile(projectDir, "next.config.mjs", "const nextConfig = {};\nexport default nextConfig;\n");
  writeFile(
    projectDir,
    "tsconfig.json",
    json({
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"]
    })
  );
}

function writeLandingPage(projectDir: string, profile: ProjectProfile) {
  writeFile(
    projectDir,
    "package.json",
    json({
      name: profile.name,
      version: "0.1.0",
      type: "module",
      scripts: { dev: "node scripts/serve.js", check: "node --check scripts/serve.js", build: "npm run check" }
    })
  );
  writeFile(
    projectDir,
    "index.html",
    '<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1">\n    <title>AgentKick Launch</title>\n    <link rel="stylesheet" href="styles.css">\n  </head>\n  <body>\n    <main class="hero">\n      <p class="eyebrow">Agent-ready from day one</p>\n      <h1>Launch faster with Codex, Claude, Cursor, and GitHub ready.</h1>\n      <p>Create the product, repo instructions, commands, and launch checklist together.</p>\n      <a href="https://github.com/" class="cta">Star on GitHub</a>\n    </main>\n  </body>\n</html>\n'
  );
  writeFile(
    projectDir,
    "styles.css",
    ":root { color-scheme: light; --ink: #1d1912; --paper: #f4ead7; --accent: #b7442e; }\nbody { margin: 0; min-height: 100vh; font-family: Georgia, serif; background: radial-gradient(circle at top left, #ffd9a3, transparent 35%), var(--paper); color: var(--ink); }\n.hero { max-width: 880px; padding: 96px 28px; margin: auto; }\n.eyebrow { text-transform: uppercase; letter-spacing: .16em; font-size: 13px; }\nh1 { font-size: clamp(42px, 8vw, 88px); line-height: .92; margin: 0 0 24px; }\np { font-size: 20px; max-width: 620px; }\n.cta { display: inline-block; margin-top: 18px; padding: 14px 18px; border-radius: 999px; background: var(--accent); color: white; text-decoration: none; }\n"
  );
  writeFile(
    projectDir,
    "scripts/serve.js",
    "import http from 'node:http';\nimport fs from 'node:fs';\nimport path from 'node:path';\n\nconst server = http.createServer((request, response) => {\n  const file = request.url === '/styles.css' ? 'styles.css' : 'index.html';\n  const body = fs.readFileSync(path.resolve(file));\n  response.setHeader('content-type', file.endsWith('.css') ? 'text/css' : 'text/html');\n  response.end(body);\n});\n\nserver.listen(3000, () => console.log('http://localhost:3000'));\n"
  );
  writeFile(projectDir, "netlify.toml", '[build]\n  publish = "."\n  command = "npm run build"\n');
}

function writeNodeCli(projectDir: string, profile: ProjectProfile) {
  writeFile(
    projectDir,
    "package.json",
    json({
      name: profile.name,
      version: "0.1.0",
      type: "module",
      bin: { [profile.name]: "./bin/cli.js" },
      scripts: { check: "node --check bin/cli.js", test: "npm run check" }
    })
  );
  writeFile(projectDir, "bin/cli.js", "#!/usr/bin/env node\nconsole.log('Hello from your AgentKick CLI.');\n");
}

function writeFastApi(projectDir: string, profile: ProjectProfile) {
  writeFile(
    projectDir,
    "pyproject.toml",
    pythonProject(profile, "FastAPI app generated by AgentKick.", ["fastapi", "uvicorn[standard]"], ["pytest", "httpx"])
  );
  writeFile(
    projectDir,
    "app/main.py",
    'from fastapi import FastAPI\n\napp = FastAPI(title="AgentKick FastAPI App")\n\n\n@app.get("/")\ndef read_root():\n    return {"status": "ok", "service": "agentkick"}\n'
  );
  writeFile(
    projectDir,
    "tests/test_health.py",
    'from fastapi.testclient import TestClient\n\nfrom app.main import app\n\n\ndef test_read_root():\n    client = TestClient(app)\n    response = client.get("/")\n    assert response.status_code == 200\n    assert response.json()["status"] == "ok"\n'
  );
  writeFile(
    projectDir,
    "Dockerfile",
    'FROM python:3.12-slim\nWORKDIR /app\nCOPY pyproject.toml ./\nRUN pip install --no-cache-dir .\nCOPY app ./app\nCMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]\n'
  );
}

function writeFlask(projectDir: string, profile: ProjectProfile) {
  writeFile(
    projectDir,
    "pyproject.toml",
    pythonProject(profile, "Flask app generated by AgentKick.", ["flask"], ["pytest"])
  );
  writeFile(
    projectDir,
    "app/__init__.py",
    'from flask import Flask\n\n\ndef create_app():\n    app = Flask(__name__)\n\n    @app.get("/")\n    def index():\n        return {"status": "ok", "service": "agentkick"}\n\n    return app\n'
  );
  writeFile(projectDir, "wsgi.py", "from app import create_app\n\napp = create_app()\n");
  writeFile(
    projectDir,
    "tests/test_app.py",
    'from app import create_app\n\n\ndef test_index():\n    app = create_app()\n    client = app.test_client()\n    response = client.get("/")\n    assert response.status_code == 200\n    assert response.json["status"] == "ok"\n'
  );
}

function writeLaravel(projectDir: string, profile: ProjectProfile) {
  writeFile(
    projectDir,
    "composer.json",
    json({
      name: `${profile.name}/app`,
      description: "Laravel app scaffold metadata generated by AgentKick.",
      type: "project",
      require: { php: "^8.2", "laravel/framework": "^12.0" },
      scripts: { test: "php artisan test" }
    })
  );
  writeFile(
    projectDir,
    "artisan",
    '#!/usr/bin/env php\n<?php\n\necho "Install Laravel dependencies or replace this placeholder with a full Laravel app.\\n";\n'
  );
  writeFile(
    projectDir,
    "routes/web.php",
    "<?php\n\nuse Illuminate\\Support\\Facades\\Route;\n\nRoute::get('/', function () {\n    return ['status' => 'ok', 'service' => 'agentkick'];\n});\n"
  );
  writeFile(
    projectDir,
    "tests/Feature/HealthTest.php",
    "<?php\n\ntest('application returns ok', function () {\n    $response = $this->get('/');\n    $response->assertOk();\n});\n"
  );
}

function writeGoCli(projectDir: string, profile: ProjectProfile) {
  writeFile(projectDir, "go.mod", `module ${goModuleName(profile.name)}\n\ngo 1.23\n`);
  writeFile(
    projectDir,
    "main.go",
    'package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println(message())\n}\n\nfunc message() string {\n\treturn "Hello from your AgentKick Go CLI."\n}\n'
  );
  writeFile(
    projectDir,
    "main_test.go",
    'package main\n\nimport "testing"\n\nfunc TestMessage(t *testing.T) {\n\tif message() == "" {\n\t\tt.Fatal("message should not be empty")\n\t}\n}\n'
  );
}

function writeRustCli(projectDir: string, profile: ProjectProfile) {
  writeFile(
    projectDir,
    "Cargo.toml",
    `[package]\nname = "${profile.name}"\nversion = "0.1.0"\nedition = "2021"\n\n[dependencies]\n`
  );
  writeFile(
    projectDir,
    "src/main.rs",
    'fn main() {\n    println!("{}", message());\n}\n\nfn message() -> &\'static str {\n    "Hello from your AgentKick Rust CLI."\n}\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n\n    #[test]\n    fn message_is_not_empty() {\n        assert!(!message().is_empty());\n    }\n}\n'
  );
}

function writeElectron(projectDir: string, profile: ProjectProfile) {
  writeFile(
    projectDir,
    "package.json",
    json({
      name: profile.name,
      version: "0.1.0",
      type: "module",
      main: "src/main.js",
      scripts: {
        dev: "electron .",
        check: "node --check src/main.js && node --check src/preload.js && node --check src/renderer.js",
        test: "npm run check",
        build: "npm run check"
      },
      devDependencies: { electron: "latest" }
    })
  );
  writeFile(
    projectDir,
    "src/main.js",
    "import { app, BrowserWindow } from 'electron';\nimport path from 'node:path';\nimport { fileURLToPath } from 'node:url';\n\nconst __dirname = path.dirname(fileURLToPath(import.meta.url));\n\nfunction createWindow() {\n  const window = new BrowserWindow({ width: 980, height: 680, webPreferences: { preload: path.join(__dirname, 'preload.js') } });\n  window.loadFile(path.join(__dirname, 'index.html'));\n}\n\napp.whenReady().then(createWindow);\napp.on('window-all-closed', () => {\n  if (process.platform !== 'darwin') app.quit();\n});\n"
  );
  writeFile(
    projectDir,
    "src/preload.js",
    "window.addEventListener('DOMContentLoaded', () => {\n  document.body.dataset.agentkick = 'ready';\n});\n"
  );
  writeFile(
    projectDir,
    "src/renderer.js",
    "document.querySelector('#status').textContent = 'AgentKick desktop app ready.';\n"
  );
  writeFile(
    projectDir,
    "src/index.html",
    htmlPage(
      "AgentKick Electron App",
      '<p id="status">Loading...</p>',
      '<script type="module" src="renderer.js"></script>'
    )
  );
  writeFile(
    projectDir,
    "src/styles.css",
    "body { margin: 0; font-family: Georgia, serif; background: #101820; color: #f8f0df; }\nmain { min-height: 100vh; display: grid; place-content: center; padding: 32px; }\nh1 { font-size: 52px; margin: 0 0 12px; }\n"
  );
}

function pythonProject(
  profile: ProjectProfile,
  description: string,
  dependencies: string[],
  devDependencies: string[]
) {
  return `[project]\nname = "${profile.name}"\nversion = "0.1.0"\ndescription = "${description}"\nrequires-python = ">=3.11"\ndependencies = [\n${dependencies.map((item) => `  "${item}"`).join(",\n")}\n]\n\n[project.optional-dependencies]\ndev = [${devDependencies.map((item) => `"${item}"`).join(", ")}]\n\n[tool.pytest.ini_options]\ntestpaths = ["tests"]\n`;
}

function htmlPage(title: string, body: string, script: string) {
  return `<!doctype html>\n<html>\n  <head>\n    <meta charset="utf-8">\n    <link rel="stylesheet" href="styles.css">\n  </head>\n  <body>\n    <main>\n      <h1>${title}</h1>\n      ${body}\n    </main>\n    ${script}\n  </body>\n</html>\n`;
}

function gitignoreFor(profile: ProjectProfile) {
  const common = [".DS_Store", ".env", ".env.local", "dist/", "build/"];
  const byStack: string[] = [];
  if (profile.stack.some((item) => ["javascript", "typescript", "nextjs", "electron", "node-cli"].includes(item)))
    byStack.push("node_modules/", ".next/", "out/");
  if (profile.stack.includes("python")) byStack.push(".venv/", "__pycache__/", "*.pyc", ".pytest_cache/");
  if (profile.stack.includes("php") || profile.stack.includes("laravel"))
    byStack.push("vendor/", "storage/logs/*.log", ".phpunit.result.cache");
  if (profile.stack.includes("go")) byStack.push("*.test", "coverage.out");
  if (profile.stack.includes("rust")) byStack.push("target/");
  return `${[...new Set([...common, ...byStack])].join("\n")}\n`;
}

function goModuleName(name: string) {
  return name.replace(/[^a-zA-Z0-9/_-]/g, "-").replace(/^-+|-+$/g, "") || "agentkick-app";
}

function titleize(value: string) {
  return value
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}
